version: 1.2
workflows:
   - subclass: CWL
     primaryDescriptorPath: /hello_world.cwl
     testParameterFiles:
         - /test.json
  - name: testApps
     subclass: CWL
     primaryDescriptorPath: /hello_world.cwl
     testParameterFiles:
         - /test.json
